# Generated by Django 6.0.4 on 2026-04-13 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_rename_is_created_task_is_compleated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='is_compleated',
            new_name='is_completed',
        ),
    ]
